### ISSUE TITLE
命令行输入sklearn-doc-zh报错，该如何解决？

### ISSUE THREAD

**Issue by haojun1993** [apachecn/sklearn-doc-zh#431]
C:\XXX>sklearn-doc-zh 8889
Traceback (most recent call last):
  File "c:\XXX\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\XXX\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\XXX\anaconda3\Scripts\sklearn-doc-zh.exe\__main__.py", line 7, in <module>
  File "c:\XXX\anaconda3\lib\site-packages\SklearnDocZh\__main__.py", line 17, in main
    svr = ThreadingHTTPServer(addr, SimpleHTTPRequestHandler)
  File "c:\XXX\anaconda3\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "c:\XXX\anaconda3\lib\http\server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "c:\XXX\anaconda3\lib\socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 3: invalid start byte

**Comment by haojun1993** [comment]
已解决，win10里面设置-时间和语言-语言-管理语言设置-管理-更改系统区域设置-Beta版：使用Unicode UTF-8提供全球语言支持
